version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 557690612191.dkr.ecr.us-east-1.amazonaws.com
      - echo "Setting up environment for ${ENV_FILE:-test}"
      - export WORDPRESS_DB_PASSWORD=${CODEBUILD_WORDPRESS_DB_PASSWORD:-default_password}
      - export MYSQL_ROOT_PASSWORD=${CODEBUILD_MYSQL_ROOT_PASSWORD:-default_root_password}

  build:
    commands:
      - echo "Building the Docker image for ${ENV_FILE:-test}"
      - docker build --build-arg ENV_FILE=${ENV_FILE:-test.env} -t 557690612191.dkr.ecr.us-east-1.amazonaws.com/wp-ecr:${ENV_FILE:-test} .
      - docker tag 557690612191.dkr.ecr.us-east-1.amazonaws.com/wp-ecr:${ENV_FILE:-test} 557690612191.dkr.ecr.us-east-1.amazonaws.com/wp-ecr:latest

  post_build:
    commands:
      - echo "Pushing the Docker image"
      - docker push 557690612191.dkr.ecr.us-east-1.amazonaws.com/wp-ecr:${ENV_FILE:-test}
      - docker push 557690612191.dkr.ecr.us-east-1.amazonaws.com/wp-ecr:latest

      - echo "Ensuring namespace $NAMESPACE
