apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Change to "elb" if needed
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
